### ISSUE TITLE
Whatsapp Web notifications have no profile picture

### ISSUE THREAD

**Issue by TheGITofTeo997** [yokoffing/Better-Fox#1]
Hello! I applied the full list user.js, all works flawlessy except this little issue. I get notifications from whatsapp web correctly, but they have no profile picture, i just get a blank space.

**Comment by yokoffing** [comment]
Hey! Thank you for using the user.js!

Can you post a screenshot, please? Also, what URL/website or extension you are using.

**Comment by TheGITofTeo997** [comment]
Hello, and sorry for the late response! Just to let you know i am the same guy on reddit who asked for smooth scrolling/typing and that is enjoying this user.js ;-) 
So basically this happens, as you will see in my screenshot in web.whatsapp.com (not happening on Telegram web)
![Cattura](https://user-images.githubusercontent.com/26879664/83014031-411b6980-a01e-11ea-904e-003411364941.PNG)

Notable to say that i am using many extensions in Firefox such as uBlock Origin, User agent Spoofer, Decentraleyes, Privacy Badger, Popup blocker Strict, Tampermonkey (just for anti adblock killer) and Smart HTTPS.
Thanks for the support and keep it up

**Comment by yokoffing** [comment]
> Hello, and sorry for the late response!

Issue reports can sometimes go on for weeks and months, so you are okay to take your time lol.

> Just to let you know i am the same guy on reddit who asked for smooth scrolling/typing and that is enjoying this user.js ;-)

Hey friend! Good to hear from you again! ;) 

> So basically this happens, as you will see in my screenshot in web.whatsapp.com (not happening on Telegram web)

I've created an account and logged in. I do not use WhatsApp, so I don't have anyone to test notifications with. If you'd like I can try sending a few messages with you so I can get an idea of what's going on. If you're open to that, send me your WhatsApp / phone number via a private message on Reddit.

I also see they have a Windows and Mac app. Have you tried using that to see if you experience any issues?

> i am using many extensions in Firefox such as uBlock Origin, User agent Spoofer, Decentraleyes, Privacy Badger, Popup blocker Strict, Tampermonkey (just for anti adblock killer) and Smart HTTPS.

A few notes here:

- Make sure **User Agent Spoofer** is whitelisted/disabled when using `web.whatsapp.com`.
- I know **Privacy Badger** has some heuristic blocking outside of vanilla blocklist-style blocking, but to my knowledge it only applies to third-party cookies; and even then, it takes three or four websites of tracking you to kick in. [With Betterfox user.js, I have third-party cookies disabled by default](https://github.com/yokoffing/Better-Fox/blob/268a83fbb92f3a0cf4f5846c552b77921320598e/user.js#L37). You can remove Privacy Badger from Firefox altogether.
- [uBlock Origin can handle popups](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups), so you can remove **Popup Blocker Strict**. The icon looks different now that uBlock Origin just got a refreshed UI, but the functionality is still there. When you hover over the icon, it will say, "Click to block all popups on this site". Just click that icon on any sites you experience annoying popups.
- You don't need **Smart HTTPS** due to [these settings in the user.js](https://github.com/yokoffing/Better-Fox/blob/268a83fbb92f3a0cf4f5846c552b77921320598e/user.js#L64-L68). Here's the [description in SecureFox](https://github.com/yokoffing/Better-Fox/blob/268a83fbb92f3a0cf4f5846c552b77921320598e/SecureFox.js#L163-L186).
- You can also trash **Tampermonkey** if you're using it solely for anti-adblock. To improve anti-ablock in uBlock Origin:
  - Be sure you have Fanboy's Enhanced Tracking List checked under "Privacy".
  - AdGuard Annoyances, Fanboy's Annoyance, and uBlock filters - Annoyances checked under the "Annoyances" subheading.

I recommend adding these custom filter lists: (Here's[ how to add custom filters to uBlock Origin](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web#import-external-filter-lists))
  1. [Nano filters](https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt) and [Nano Placeholder Buster](https://raw.githubusercontent.com/NanoAdblockerLab/NanoContrib/master/dist/placeholder-buster.txt) - using these two list alone in uBlock Origin really help with pesky anti-adblocking.
  2. [dbl.osid](https://abp.oisd.nl/) - my number one recommended domain list. [The goal is to have zero false positives but awesome privacy and security](https://www.reddit.com/r/oisd_blocklist/comments/gjn972/abpoisdnl_internets_1_domain_blocklist/). I contribute to this list a lot. There's a ton of entries, but no worries! uBlock Origin is able to handle large lists very well.
  3. [Fuck Fuckadblock](https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt)
  4. [uBlock Filters Plus](https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt) to handle some pop-unders and redirects. You'll still need to manually block pop-ups on some sites, as discussed earlier.

That was a lot! I hope this information makes your browser more streamlined and efficient.

**Comment by TheGITofTeo997** [comment]
Wow, thanks for the long answer and for all the tips ;-) Ok so regarding the Whatsapp issue i tried disabling ALL the addons i had but unfortunately the issue still occurs. To give a possible help i wrote to you on Reddit Direct

**Comment by yokoffing** [comment]
Third-party cookie blocking issue. Add `https://web.whatsapp.com` to Firefox's Exceptions: Cookies and Site Data.
