### ISSUE TITLE
Value of network.http.speculative-parallel-limit is different in the user.js(6) and comparison table(0).

### ISSUE THREAD

**Issue by Rtizer-9** [yokoffing/Better-Fox#16]
What's your preferred value?
PS: While I was writing this I also came across different setting for cookiebehavior. It's kinda confusing which value do we have to use.

**Comment by yokoffing** [comment]
The comparison table of user.js files is outdated; it's inconvenient to update. What I might do is put a note of when it was last updated and set a reminder for myself to update it at least once or twice a year (i.e. core prefs don't change often). I'll add this to my to-do list.

As an aside: The comparison table doesn't take into account values that are commented out with `/*` or `//`. For gits like Arkenfox, they keep some commented out prefs while keeping them in the user.js. I try to keep my commented-out prefs to the individual sections (SecureFox, PeskyFox, etc.). TL;DR: just because it's in the comparison table doesn't mean a pref is recommended. Just something to be aware of.

You should be reading through the individual sections (FastFox, SecureFox, etc.) to know what a pref controls and why you're changing it. There's descriptions and links for most prefs.

(You can download the user.js with everything preconfigured, but if you're curious about a pref, please read the individual files.)

`network.http.speculative-parallel-limit` is at `6` which is the Firefox default but [will be changed](https://github.com/yokoffing/Better-Fox/pull/14/commits/fb22f6a12c8181b8a245c9f81284a1f3b4ba449b) to `0` once I release [updates for March 2021](https://github.com/yokoffing/Better-Fox/pull/13/files).

`cookiebehavior` should be `5`.
