### ISSUE TITLE
[BUG] graad.eu Website gets broken css

### ISSUE THREAD

**Issue by TheGITofTeo997** [yokoffing/Better-Fox#44]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [X] [Cleared website data](https://www.hostinger.com/tutorials/wp-content/uploads/sites/2/2018/05/clear-browser-cache-firefox.png), restarted Firefox, and my issue persists.
- [X] No issues when using the website or extension in another web browser.
- [X] The issue persists when using Firefox in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode#w_how-to-start-firefox-in-safe-mode).
- [X] Disabled DNS-level content blocking (AdGuard, NextDNS, PiHole), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).

## REPORT
**Describe the bug**
When browsing the website graad.eu with user.js full list applied, some css files won't get loaded and the website is not displayed correctly, between those files we have: default.css, theme.css, queries.css

**To Reproduce**
1. Go to 'graad.eu'
2. See error

**Expected behavior**
The website should be displayed correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Version [94]

![Immagine 2021-11-03 225257](https://user-images.githubusercontent.com/26879664/140198292-e80c2b7d-f6b4-4094-854d-c723c662ace2.png)

**Comment by chrmod** [comment]
This website try to `preload` the CSS. 
https://github.com/ghostery/user-agent-desktop/issues/582#issuecomment-963156621

Not sure if that makes any sense or if that's some Firefox bug. 

Anyways, breakage is caused by `network.preload` being set to `false`.

We should probably report this to Mozilla.

**Comment by TheGITofTeo997** [comment]
Thanks for the hint.
I can confirm the website works correctly with `network.preload` set to true.

Now my question is if it's convenient to leave that to true, and most importantly if in any way it defeats the purpose of speed and stability of this project, because if so, even if it's a temporary fix we could say, of course it's not worth it to leave that to true. 

Thanks for digging into this more, and please let me know if something by my end is needed to give an help with this.

**Comment by yokoffing** [comment]
https://github.com/yokoffing/Better-Fox/blob/41d94c01d19505f726fddbea7e431737d78b8724/SecureFox.js#L245-L260

@chrmod I also wonder if it loads properly in other browsers with`<link rel=preload>` disabled, if there's a way to even turn it off. Unfortunately, Chromium has base-level prefetching even if a user disables `Preload pages for faster browsing and searching` (see https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#important-note and https://github.com/gorhill/uBlock/issues/3219#issuecomment-343688207). I'm not sure about Safari or other Webkit browsers.

This makes me wonder if `https://www.graad.eu` is formatted in such a way that these stylesheets are only set to load through `network.preload` (i.e., there's no alternative way of loading those resources, so the page breaks).

***

@TheGITofTeo997 I would file a bug report: https://bugzilla.mozilla.org/enter_bug.cgi.

> if in any way it defeats the purpose of speed and stability of this project

### Stability
As far as leaving `network.preload` set to `true` all the time, note my warning:
https://github.com/yokoffing/Better-Fox/blob/41d94c01d19505f726fddbea7e431737d78b8724/SecureFox.js#L253

For instance, you can disable uBlock Origin's `Disable pre-fetching (to prevent any connection for blocked network requests)` and enable all of settings below in Firefox _except_ `network.preload`, and they won't interfere with blocking ads, annoyances, etc. on the page.
https://github.com/yokoffing/Better-Fox/blob/41d94c01d19505f726fddbea7e431737d78b8724/user.js#L57-L64

However, occasional ads or annoyances are not blocked with `network.preload` set to `true`, so I would not advise leaving it on.

### Speed

Chrome (by default) aggressively prefetches/preloads resources, and it's part of why it's so fast. In my experience, it's preloading is also much better compared to Firefox, when neither of them using content blockers (e.g., Ghostery, uBlock Origin).

_Without_ a content blocker and preloading enabled: preloading does make a significant difference in page loading.

_With_ a content blocker and preloading enabled: network requests (like trackers and annoyances) you otherwise would block will connect regardless of your content blocker settings. You save a significant amount of time in page loading by blocking trackers anyway, especially if you block a lot of third-party requests like my [Privacy Essentials](https://github.com/yokoffing/filterlists/blob/main/PrivacyEssentials.txt) list includes. Total page load time should be quicker than preloading without a content blocker, but content painting on the page can sometimes be a bit delayed; it depends on the site. Overall, it should be faster. Other issues may arise when you mix preloading with content blocking (like the one we're discussing above).

I hope that makes sense.

**Comment by yokoffing** [comment]
I have filed a bug report with Mozilla. https://bugzilla.mozilla.org/show_bug.cgi?id=1754264
